In [1]:
import pandas as pd
import random
from datetime import datetime, timedelta

In [2]:
apps = {
    "Instagram": "Social Media",
    "WhatsApp": "Social Media",
    "YouTube": "Entertainment",
    "Netflix": "Entertainment",
    "VS Code": "Coding",
    "Google Colab": "Coding",
    "Coursera": "Education",
    "Google": "Education",
    "Notion": "Productivity",
    "Spotify": "Entertainment"
}

In [3]:
data = []

start_date = datetime(2026, 8, 1)

for i in range(14):
    date = (start_date + timedelta(days=i)).strftime("%Y-%m-%d")

    for app, category in apps.items():
        minutes = random.randint(15, 120)

        data.append([
            date,
            app,
            category,
            minutes
        ])

In [4]:
df = pd.DataFrame(
    data,
    columns=["Date", "App_Name", "Category", "Minutes_Used"]
)

df.head(10)

         Date      App_Name       Category  Minutes_Used
0  2026-08-01     Instagram   Social Media            67
1  2026-08-01      WhatsApp   Social Media            95
2  2026-08-01       YouTube  Entertainment            66
3  2026-08-01       Netflix  Entertainment            30
4  2026-08-01       VS Code         Coding            83
5  2026-08-01  Google Colab         Coding            61
6  2026-08-01      Coursera      Education            62
7  2026-08-01        Google      Education            15
8  2026-08-01        Notion   Productivity            26
9  2026-08-01       Spotify  Entertainment            82

In [5]:
print("Total Rows:", len(df))
print("Total Days:", df["Date"].nunique())
print("Total Apps:", df["App_Name"].nunique())

Total Rows: 140
Total Days: 14
Total Apps: 10

In [6]:
df.to_csv("screentime.csv", index=False)

print("✅ screentime.csv created successfully!")

✅ screentime.csv created successfully!

In [7]:
df = pd.read_csv("screentime.csv")

df.head()

         Date   App_Name       Category  Minutes_Used
0  2026-08-01  Instagram   Social Media            67
1  2026-08-01   WhatsApp   Social Media            95
2  2026-08-01    YouTube  Entertainment            66
3  2026-08-01    Netflix  Entertainment            30
4  2026-08-01    VS Code         Coding            83

In [8]:
category_usage = (
    df.groupby("Category")["Minutes_Used"]
    .sum()
    .sort_values(ascending=False)
)

category_usage

Category
Entertainment    2945
Coding           2246
Education        1821
Social Media     1681
Productivity      884
Name: Minutes_Used, dtype: int64

In [9]:
daily_usage = (
    df.groupby("Date")["Minutes_Used"]
    .sum()
)

daily_usage

Date
2026-08-01    587
2026-08-02    728
2026-08-03    762
2026-08-04    630
2026-08-05    565
2026-08-06    760
2026-08-07    804
2026-08-08    670
2026-08-09    614
2026-08-10    793
2026-08-11    798
2026-08-12    658
2026-08-13    562
2026-08-14    646
Name: Minutes_Used, dtype: int64

In [10]:
import os
os.getcwd()

'C:\\Users\\pranj\\Life-OS'

In [11]:
os.listdir()

[' requirements.txt',
 '.ipynb_checkpoints',
 'app.py',
 'Life_OS.ipynb',
 'README.md',
 'screentime.csv',
 'Untitled.ipynb']

In [12]:
import pandas as pd

data = [
    # Day 1 - Balanced
    ["2026-08-01", "VS Code", "Coding", 150],
    ["2026-08-01", "Google Colab", "Coding", 60],
    ["2026-08-01", "Coursera", "Education", 75],
    ["2026-08-01", "Instagram", "Social Media", 45],
    ["2026-08-01", "YouTube", "Entertainment", 50],
    ["2026-08-01", "Notion", "Productivity", 40],

    # Day 2 - High social media
    ["2026-08-02", "VS Code", "Coding", 90],
    ["2026-08-02", "Coursera", "Education", 40],
    ["2026-08-02", "Instagram", "Social Media", 160],
    ["2026-08-02", "WhatsApp", "Social Media", 70],
    ["2026-08-02", "YouTube", "Entertainment", 120],
    ["2026-08-02", "Notion", "Productivity", 30],

    # Day 3 - Productive
    ["2026-08-03", "VS Code", "Coding", 180],
    ["2026-08-03", "Google Colab", "Coding", 90],
    ["2026-08-03", "Coursera", "Education", 100],
    ["2026-08-03", "Instagram", "Social Media", 30],
    ["2026-08-03", "YouTube", "Entertainment", 45],
    ["2026-08-03", "Notion", "Productivity", 50],

    # Day 4 - Entertainment heavy
    ["2026-08-04", "VS Code", "Coding", 70],
    ["2026-08-04", "Coursera", "Education", 30],
    ["2026-08-04", "Instagram", "Social Media", 100],
    ["2026-08-04", "YouTube", "Entertainment", 150],
    ["2026-08-04", "Netflix", "Entertainment", 120],
    ["2026-08-04", "Notion", "Productivity", 25],

    # Day 5 - Balanced
    ["2026-08-05", "VS Code", "Coding", 140],
    ["2026-08-05", "Google Colab", "Coding", 50],
    ["2026-08-05", "Coursera", "Education", 80],
    ["2026-08-05", "Instagram", "Social Media", 55],
    ["2026-08-05", "YouTube", "Entertainment", 60],
    ["2026-08-05", "Notion", "Productivity", 45],

    # Day 6 - Bad day
    ["2026-08-06", "VS Code", "Coding", 45],
    ["2026-08-06", "Coursera", "Education", 20],
    ["2026-08-06", "Instagram", "Social Media", 190],
    ["2026-08-06", "WhatsApp", "Social Media", 80],
    ["2026-08-06", "YouTube", "Entertainment", 150],
    ["2026-08-06", "Netflix", "Entertainment", 100],

    # Day 7 - Productive
    ["2026-08-07", "VS Code", "Coding", 200],
    ["2026-08-07", "Google Colab", "Coding", 70],
    ["2026-08-07", "Coursera", "Education", 90],
    ["2026-08-07", "Instagram", "Social Media", 35],
    ["2026-08-07", "YouTube", "Entertainment", 40],
    ["2026-08-07", "Notion", "Productivity", 60],

    # Day 8 - Weekend entertainment
    ["2026-08-08", "VS Code", "Coding", 60],
    ["2026-08-08", "Coursera", "Education", 30],
    ["2026-08-08", "Instagram", "Social Media", 140],
    ["2026-08-08", "YouTube", "Entertainment", 160],
    ["2026-08-08", "Netflix", "Entertainment", 130],
    ["2026-08-08", "Spotify", "Entertainment", 60],

    # Day 9 - Balanced
    ["2026-08-09", "VS Code", "Coding", 130],
    ["2026-08-09", "Google Colab", "Coding", 60],
    ["2026-08-09", "Coursera", "Education", 70],
    ["2026-08-09", "Instagram", "Social Media", 50],
    ["2026-08-09", "YouTube", "Entertainment", 70],
    ["2026-08-09", "Notion", "Productivity", 40],

    # Day 10 - Social media heavy
    ["2026-08-10", "VS Code", "Coding", 80],
    ["2026-08-10", "Coursera", "Education", 35],
    ["2026-08-10", "Instagram", "Social Media", 180],
    ["2026-08-10", "WhatsApp", "Social Media", 90],
    ["2026-08-10", "YouTube", "Entertainment", 110],
    ["2026-08-10", "Notion", "Productivity", 25],

    # Day 11 - Productive
    ["2026-08-11", "VS Code", "Coding", 190],
    ["2026-08-11", "Google Colab", "Coding", 80],
    ["2026-08-11", "Coursera", "Education", 100],
    ["2026-08-11", "Instagram", "Social Media", 25],
    ["2026-08-11", "YouTube", "Entertainment", 35],
    ["2026-08-11", "Notion", "Productivity", 55],

    # Day 12 - Entertainment heavy
    ["2026-08-12", "VS Code", "Coding", 75],
    ["2026-08-12", "Coursera", "Education", 30],
    ["2026-08-12", "Instagram", "Social Media", 110],
    ["2026-08-12", "YouTube", "Entertainment", 170],
    ["2026-08-12", "Netflix", "Entertainment", 100],
    ["2026-08-12", "Notion", "Productivity", 30],

    # Day 13 - Weekend bad
    ["2026-08-13", "VS Code", "Coding", 50],
    ["2026-08-13", "Coursera", "Education", 25],
    ["2026-08-13", "Instagram", "Social Media", 170],
    ["2026-08-13", "WhatsApp", "Social Media", 75],
    ["2026-08-13", "YouTube", "Entertainment", 180],
    ["2026-08-13", "Netflix", "Entertainment", 120],

    # Day 14 - Strong finish
    ["2026-08-14", "VS Code", "Coding", 210],
    ["2026-08-14", "Google Colab", "Coding", 70],
    ["2026-08-14", "Coursera", "Education", 110],
    ["2026-08-14", "Instagram", "Social Media", 30],
    ["2026-08-14", "YouTube", "Entertainment", 40],
    ["2026-08-14", "Notion", "Productivity", 65],
]

df = pd.DataFrame(
    data,
    columns=["Date", "App_Name", "Category", "Minutes_Used"]
)

df.to_csv("screentime.csv", index=False)

print("✅ Realistic synthetic dataset created!")
print("Rows:", len(df))
print("Days:", df["Date"].nunique())

✅ Realistic synthetic dataset created!
Rows: 84
Days: 14

In [13]:
df.head()

         Date      App_Name       Category  Minutes_Used
0  2026-08-01       VS Code         Coding           150
1  2026-08-01  Google Colab         Coding            60
2  2026-08-01      Coursera      Education            75
3  2026-08-01     Instagram   Social Media            45
4  2026-08-01       YouTube  Entertainment            50

In [14]:
df.groupby("Date")["Minutes_Used"].sum()

Date
2026-08-01    420
2026-08-02    510
2026-08-03    495
2026-08-04    495
2026-08-05    430
2026-08-06    585
2026-08-07    495
2026-08-08    580
2026-08-09    420
2026-08-10    520
2026-08-11    485
2026-08-12    515
2026-08-13    620
2026-08-14    525
Name: Minutes_Used, dtype: int64